#!/bin/bash
set -euo pipefail
cd /app
python - <<'PYFIX'
from pathlib import Path
p = Path('clinic/repositories/workload.py')
assert p.read_text() == 'from django.db import models\nfrom django.db.models.functions import Coalesce\n\nfrom clinic.models import Appointment, Doctor\n\n\ndef doctor_workload(clinic_id, as_of):\n    """Return the clinic roster with approved session minutes and future open slots."""\n    return (Doctor.objects.filter(clinic_id=clinic_id)\n            .annotate(approved_minutes=Coalesce(models.Sum(\'sessions__minutes\',\n                      filter=models.Q(sessions__approved=True)), models.Value(0)),\n                      open_appointments=models.Value(0, output_field=models.IntegerField()))\n            .order_by(\'display_name\', \'id\'))\n\n\ndef appointment_overview(clinic_id):\n    """Separate administration endpoint; preserve its grouped counts."""\n    return list(Appointment.objects.filter(doctor__clinic_id=clinic_id).values(\'state\')\n                .annotate(total=models.Count(\'id\')).order_by(\'state\'))\n', "source anchor changed"
p.write_text('from django.db import models\nfrom django.db.models.functions import Coalesce\n\nfrom clinic.models import Appointment, Doctor\n\n\ndef doctor_workload(clinic_id, as_of):\n    """Return the clinic roster with approved session minutes and future open slots."""\n    counts = (Appointment.objects.filter(doctor_id=models.OuterRef(\'pk\'), state=\'open\', starts_at__gte=as_of)\n              .order_by().values(\'doctor_id\').annotate(total=models.Count(\'id\')).values(\'total\'))\n    count_expression = Coalesce(models.Subquery(counts, output_field=models.IntegerField()),\n                                models.Value(0), output_field=models.IntegerField())\n    return (Doctor.objects.filter(clinic_id=clinic_id)\n            .annotate(approved_minutes=Coalesce(models.Sum(\'sessions__minutes\',\n                      filter=models.Q(sessions__approved=True)), models.Value(0)),\n                      open_appointments=count_expression)\n            .order_by(\'display_name\', \'id\'))\n\n\ndef appointment_overview(clinic_id):\n    """Separate administration endpoint; preserve its grouped counts."""\n    return list(Appointment.objects.filter(doctor__clinic_id=clinic_id).values(\'state\')\n                .annotate(total=models.Count(\'id\')).order_by(\'state\'))\n')
PYFIX
