#!/bin/bash
set -euo pipefail
cd /app
python - <<'PYFIX'
from pathlib import Path
p = Path('app/reports.py')
assert p.read_text() == 'from sqlalchemy import (\n    Column,\n    DateTime,\n    Integer,\n    MetaData,\n    String,\n    Table,\n    and_,\n    func,\n    select,\n)\n\nmetadata = MetaData()\nevents = Table(\'events\', metadata, Column(\'id\', Integer, primary_key=True), Column(\'customer_id\', Integer),\n               Column(\'occurred_at\', DateTime(timezone=True)), Column(\'status\', String))\n\n\ndef latest_per_customer(conn, since, until):\n    """Return (customer_id, event_id, occurred_at) for each latest event in [since, until)."""\n    newest = select(events.c.customer_id, func.max(events.c.occurred_at).label(\'ts\')).where(\n        events.c.occurred_at >= since, events.c.occurred_at < until).group_by(events.c.customer_id).subquery()\n    query = select(events.c.customer_id, events.c.id, events.c.occurred_at).join(\n        newest, and_(events.c.customer_id == newest.c.customer_id, events.c.occurred_at == newest.c.ts))\n    return list(conn.execute(query.order_by(events.c.customer_id)))\n', "source anchor changed"
p.write_text('from sqlalchemy import (\n    Column,\n    DateTime,\n    Integer,\n    MetaData,\n    String,\n    Table,\n    and_,\n    func,\n    select,\n)\n\nmetadata = MetaData()\nevents = Table(\'events\', metadata, Column(\'id\', Integer, primary_key=True), Column(\'customer_id\', Integer),\n               Column(\'occurred_at\', DateTime(timezone=True)), Column(\'status\', String))\n\n\ndef latest_per_customer(conn, since, until):\n    """Return (customer_id, event_id, occurred_at) for each latest event in [since, until)."""\n    ranked = select(events.c.customer_id, events.c.id, events.c.occurred_at,\n                    func.row_number().over(partition_by=events.c.customer_id,\n                                           order_by=[events.c.occurred_at.desc(), events.c.id.desc()]).label(\'rn\')).where(\n                        events.c.occurred_at >= since, events.c.occurred_at < until).subquery()\n    query = select(ranked.c.customer_id, ranked.c.id, ranked.c.occurred_at).where(and_(ranked.c.rn == 1))\n    return list(conn.execute(query.order_by(ranked.c.customer_id)))\n')
PYFIX
