#!/bin/bash
set -euo pipefail
cd /app
python3 - <<'PYFIX'
from pathlib import Path
p=Path('internal/store/report.go')
old='package store\n\nimport (\n\t"context"\n\t"gorm.io/gorm"\n)\n\ntype Store struct{ DB *gorm.DB }\ntype Customer struct {\n\tID     int64 `gorm:"primaryKey"`\n\tTenant string\n\tName   string\n\tOrders []Order\n}\ntype Order struct {\n\tID         int64 `gorm:"primaryKey"`\n\tCustomerID int64\n\tCancelled  bool\n\tItems      []Item\n}\ntype Item struct {\n\tID      int64 `gorm:"primaryKey"`\n\tOrderID int64\n\tSKU     string\n}\n\nfunc (s *Store) Customers(ctx context.Context, tenant string) ([]Customer, error) {\n\tvar customers []Customer\n\tdb := s.DB.WithContext(ctx)\n\tif err := db.Where("tenant = ?", tenant).Order("id").Find(&customers).Error; err != nil {\n\t\treturn nil, err\n\t}\n\tfor i := range customers {\n\t\tif err := db.Where("customer_id = ? AND cancelled = false", customers[i].ID).Order("id").Find(&customers[i].Orders).Error; err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\tfor j := range customers[i].Orders {\n\t\t\tif err := db.Where("order_id = ?", customers[i].Orders[j].ID).Order("id").Find(&customers[i].Orders[j].Items).Error; err != nil {\n\t\t\t\treturn nil, err\n\t\t\t}\n\t\t}\n\t}\n\treturn customers, nil\n}\n'
assert p.read_text()==old, 'source anchor changed'
p.write_text('package store\n\nimport (\n\t"context"\n\t"gorm.io/gorm"\n)\n\ntype Store struct{ DB *gorm.DB }\ntype Customer struct {\n\tID     int64 `gorm:"primaryKey"`\n\tTenant string\n\tName   string\n\tOrders []Order\n}\ntype Order struct {\n\tID         int64 `gorm:"primaryKey"`\n\tCustomerID int64\n\tCancelled  bool\n\tItems      []Item\n}\ntype Item struct {\n\tID      int64 `gorm:"primaryKey"`\n\tOrderID int64\n\tSKU     string\n}\n\nfunc (s *Store) Customers(ctx context.Context, tenant string) ([]Customer, error) {\n\tvar customers []Customer\n\tdb := s.DB.WithContext(ctx)\n\terr := db.Where("tenant = ?", tenant).Order("id").Preload("Orders", func(q *gorm.DB) *gorm.DB { return q.Where("cancelled = false").Order("id") }).Preload("Orders.Items", func(q *gorm.DB) *gorm.DB { return q.Order("id") }).Find(&customers).Error\n\treturn customers, err\n}\n')
PYFIX
