--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+2)
-- Dumped by pg_dump version 16.4 (Debian 16.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes_author; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes_author (
    id bigint NOT NULL,
    handle character varying(50) NOT NULL,
    name character varying(120) NOT NULL
);


--
-- Name: recipes_author_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes_author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes_ingredient; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes_ingredient (
    id bigint NOT NULL,
    "position" smallint NOT NULL,
    name character varying(120) NOT NULL,
    quantity character varying(60) NOT NULL,
    recipe_id bigint NOT NULL,
    CONSTRAINT recipes_ingredient_position_check CHECK (("position" >= 0))
);


--
-- Name: recipes_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes_ingredient ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes_recipe; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes_recipe (
    id bigint NOT NULL,
    slug character varying(50) NOT NULL,
    title character varying(200) NOT NULL,
    servings smallint NOT NULL,
    published boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    author_id bigint NOT NULL,
    CONSTRAINT recipes_recipe_servings_check CHECK ((servings >= 0))
);


--
-- Name: recipes_recipe_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes_recipe ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes_recipe_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes_recipe_tags (
    id bigint NOT NULL,
    recipe_id bigint NOT NULL,
    tag_id bigint NOT NULL
);


--
-- Name: recipes_recipe_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes_recipe_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_recipe_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes_review (
    id bigint NOT NULL,
    reviewer character varying(80) NOT NULL,
    rating smallint NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    recipe_id bigint NOT NULL,
    CONSTRAINT recipes_review_rating_check CHECK ((rating >= 0)),
    CONSTRAINT review_rating_range CHECK (((rating >= 1) AND (rating <= 5)))
);


--
-- Name: recipes_review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes_tag (
    id bigint NOT NULL,
    slug character varying(50) NOT NULL,
    name character varying(60) NOT NULL
);


--
-- Name: recipes_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	recipes	0001_initial	2026-09-29 13:11:21.498927+00
\.


--
-- Data for Name: recipes_author; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipes_author (id, handle, name) FROM stdin;
1	ada-quinn	Ada Quinn
2	bo-lindqvist	Bo Lindqvist
3	chidi-eze	Chidi Eze
\.


--
-- Data for Name: recipes_ingredient; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipes_ingredient (id, "position", name, quantity, recipe_id) FROM stdin;
1	1	leeks		1
2	2	potatoes		1
3	3	stock		1
4	4	butter		1
5	1	red lentils		2
6	2	onion		2
7	3	garlic		2
8	1	rye flour		3
9	1	noodles		4
10	1	flour		5
11	2	seeds		5
12	3	yeast		5
13	4	salt		5
14	5	water		5
15	1	tomatoes		6
16	2	tamarind		6
17	3	pepper		6
\.


--
-- Data for Name: recipes_recipe; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipes_recipe (id, slug, title, servings, published, created_at, author_id) FROM stdin;
1	leek-and-potato-soup	Leek and Potato Soup	2	t	2026-04-20 18:00:00+00	1
2	weeknight-dal	Weeknight Dal	3	t	2026-04-19 18:00:00+00	3
3	rye-flatbread	Rye Flatbread	4	t	2026-04-18 18:00:00+00	2
4	chilli-noodles	Chilli Noodles	2	t	2026-04-17 18:00:00+00	3
5	seeded-loaf	Seeded Loaf	3	t	2026-04-16 18:00:00+00	2
6	tomato-rasam	Tomato Rasam	4	t	2026-04-15 18:00:00+00	3
7	untested-idea	Untested Idea	2	f	2026-04-20 18:00:00+00	1
\.


--
-- Data for Name: recipes_recipe_tags; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipes_recipe_tags (id, recipe_id, tag_id) FROM stdin;
1	1	1
2	1	3
3	2	1
4	2	2
5	2	5
6	3	4
7	4	2
8	4	5
9	5	1
10	5	4
11	6	3
12	6	5
\.


--
-- Data for Name: recipes_review; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipes_review (id, reviewer, rating, body, created_at, recipe_id) FROM stdin;
1	reader-1	5		2026-04-20 19:00:00+00	1
2	reader-1	4		2026-04-18 19:00:00+00	3
3	reader-2	5		2026-04-18 20:00:00+00	3
4	reader-1	5		2026-04-17 19:00:00+00	4
5	reader-2	3		2026-04-17 20:00:00+00	4
6	reader-3	4		2026-04-17 21:00:00+00	4
7	reader-1	4		2026-04-15 19:00:00+00	6
\.


--
-- Data for Name: recipes_tag; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.recipes_tag (id, slug, name) FROM stdin;
1	vegetarian	Vegetarian
2	weeknight	Quick weeknight
3	soup	Soups
4	baking	Baking
5	spicy	Spicy
\.


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 1, true);


--
-- Name: recipes_author_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_author_id_seq', 3, true);


--
-- Name: recipes_ingredient_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_ingredient_id_seq', 17, true);


--
-- Name: recipes_recipe_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_recipe_id_seq', 7, true);


--
-- Name: recipes_recipe_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_recipe_tags_id_seq', 12, true);


--
-- Name: recipes_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_review_id_seq', 7, true);


--
-- Name: recipes_tag_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.recipes_tag_id_seq', 5, true);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: recipes_ingredient ingredient_position_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_ingredient
    ADD CONSTRAINT ingredient_position_unique UNIQUE (recipe_id, "position");


--
-- Name: recipes_author recipes_author_handle_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_author
    ADD CONSTRAINT recipes_author_handle_key UNIQUE (handle);


--
-- Name: recipes_author recipes_author_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_author
    ADD CONSTRAINT recipes_author_pkey PRIMARY KEY (id);


--
-- Name: recipes_ingredient recipes_ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_ingredient
    ADD CONSTRAINT recipes_ingredient_pkey PRIMARY KEY (id);


--
-- Name: recipes_recipe recipes_recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_recipe
    ADD CONSTRAINT recipes_recipe_pkey PRIMARY KEY (id);


--
-- Name: recipes_recipe recipes_recipe_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_recipe
    ADD CONSTRAINT recipes_recipe_slug_key UNIQUE (slug);


--
-- Name: recipes_recipe_tags recipes_recipe_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_recipe_tags
    ADD CONSTRAINT recipes_recipe_tags_pkey PRIMARY KEY (id);


--
-- Name: recipes_recipe_tags recipes_recipe_tags_recipe_id_tag_id_233281ac_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_recipe_tags
    ADD CONSTRAINT recipes_recipe_tags_recipe_id_tag_id_233281ac_uniq UNIQUE (recipe_id, tag_id);


--
-- Name: recipes_review recipes_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_review
    ADD CONSTRAINT recipes_review_pkey PRIMARY KEY (id);


--
-- Name: recipes_tag recipes_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_tag
    ADD CONSTRAINT recipes_tag_pkey PRIMARY KEY (id);


--
-- Name: recipes_tag recipes_tag_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_tag
    ADD CONSTRAINT recipes_tag_slug_key UNIQUE (slug);


--
-- Name: recipes_author_handle_c55c2163_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_author_handle_c55c2163_like ON public.recipes_author USING btree (handle varchar_pattern_ops);


--
-- Name: recipes_ingredient_recipe_id_1877a0b2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_ingredient_recipe_id_1877a0b2 ON public.recipes_ingredient USING btree (recipe_id);


--
-- Name: recipes_recipe_author_id_7274f74b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipe_author_id_7274f74b ON public.recipes_recipe USING btree (author_id);


--
-- Name: recipes_recipe_slug_b40bdd3d_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipe_slug_b40bdd3d_like ON public.recipes_recipe USING btree (slug varchar_pattern_ops);


--
-- Name: recipes_recipe_tags_recipe_id_e15a4132; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipe_tags_recipe_id_e15a4132 ON public.recipes_recipe_tags USING btree (recipe_id);


--
-- Name: recipes_recipe_tags_tag_id_6fe328c4; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_recipe_tags_tag_id_6fe328c4 ON public.recipes_recipe_tags USING btree (tag_id);


--
-- Name: recipes_review_recipe_id_0edd9726; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_review_recipe_id_0edd9726 ON public.recipes_review USING btree (recipe_id);


--
-- Name: recipes_tag_slug_baa21000_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX recipes_tag_slug_baa21000_like ON public.recipes_tag USING btree (slug varchar_pattern_ops);


--
-- Name: recipes_ingredient recipes_ingredient_recipe_id_1877a0b2_fk_recipes_recipe_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_ingredient
    ADD CONSTRAINT recipes_ingredient_recipe_id_1877a0b2_fk_recipes_recipe_id FOREIGN KEY (recipe_id) REFERENCES public.recipes_recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recipes_recipe recipes_recipe_author_id_7274f74b_fk_recipes_author_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_recipe
    ADD CONSTRAINT recipes_recipe_author_id_7274f74b_fk_recipes_author_id FOREIGN KEY (author_id) REFERENCES public.recipes_author(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recipes_recipe_tags recipes_recipe_tags_recipe_id_e15a4132_fk_recipes_recipe_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_recipe_tags
    ADD CONSTRAINT recipes_recipe_tags_recipe_id_e15a4132_fk_recipes_recipe_id FOREIGN KEY (recipe_id) REFERENCES public.recipes_recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recipes_recipe_tags recipes_recipe_tags_tag_id_6fe328c4_fk_recipes_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_recipe_tags
    ADD CONSTRAINT recipes_recipe_tags_tag_id_6fe328c4_fk_recipes_tag_id FOREIGN KEY (tag_id) REFERENCES public.recipes_tag(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: recipes_review recipes_review_recipe_id_0edd9726_fk_recipes_recipe_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes_review
    ADD CONSTRAINT recipes_review_recipe_id_0edd9726_fk_recipes_recipe_id FOREIGN KEY (recipe_id) REFERENCES public.recipes_recipe(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

