#!/bin/bash
set -euo pipefail
cd /app
python3 - <<'PYFIX'
from pathlib import Path
p = Path('src/repositories/events.ts')
assert p.read_text() == "import type { DataSource } from 'typeorm';\nimport { EventSchema, TicketTypeSchema, type VenueEvent } from '../entities.js';\n\nexport interface EventPage { items: VenueEvent[]; total: number }\n\n/** Load one page of published events and their complete ticket-type collections. */\nexport async function listEvents(source: DataSource, tenant: number, kind: string | null, offset: number, limit: number): Promise<EventPage> {\n  const query = source.getRepository(EventSchema).createQueryBuilder('event')\n    .leftJoinAndSelect('event.ticketTypes', 'ticket')\n    .where('event.tenantId = :tenant', { tenant }).andWhere('event.published = true');\n  if (kind !== null) query.andWhere('ticket.kind = :kind AND ticket.enabled = true', { kind });\n  query.orderBy('event.startsAt', 'ASC').limit(limit).offset(offset);\n  const total = (await query.clone().limit(undefined).offset(undefined).getRawMany()).length;\n  return { items: await query.getMany(), total };\n}\n\nexport async function enabledTicketKinds(source: DataSource, eventId: number): Promise<string[]> {\n  const tickets = await source.getRepository(TicketTypeSchema).find({ where: { eventId, enabled: true }, order: { id: 'ASC' } });\n  return tickets.map(ticket => ticket.kind);\n}\n", "source anchor changed"
p.write_text("import type { DataSource } from 'typeorm';\nimport { EventSchema, TicketTypeSchema, type VenueEvent } from '../entities.js';\n\nexport interface EventPage { items: VenueEvent[]; total: number }\n\n/** Load one page of published events and their complete ticket-type collections. */\nexport async function listEvents(source: DataSource, tenant: number, kind: string | null, offset: number, limit: number): Promise<EventPage> {\n  const query = source.getRepository(EventSchema).createQueryBuilder('event')\n    .leftJoinAndSelect('event.ticketTypes', 'ticket')\n    .where('event.tenantId = :tenant', { tenant }).andWhere('event.published = true');\n  if (kind !== null) {\n    query.andWhere(builder => 'EXISTS ' + builder.subQuery().select('1')\n      .from(TicketTypeSchema, 'eligible').where('eligible.eventId = event.id')\n      .andWhere('eligible.kind = :kind AND eligible.enabled = true').getQuery(), { kind });\n  }\n  query.orderBy('event.startsAt', 'ASC').addOrderBy('event.id', 'ASC').skip(offset).take(limit);\n  const [items, total] = await query.getManyAndCount();\n  return { items, total };\n}\n\nexport async function enabledTicketKinds(source: DataSource, eventId: number): Promise<string[]> {\n  const tickets = await source.getRepository(TicketTypeSchema).find({ where: { eventId, enabled: true }, order: { id: 'ASC' } });\n  return tickets.map(ticket => ticket.kind);\n}\n")
PYFIX
