#!/bin/bash
set -euo pipefail
cd /app
python - <<'PYFIX'
from pathlib import Path
p = Path('freight/repositories/tracking.py')
assert p.read_text() == 'from sqlalchemy import and_, func, select\n\nfrom freight.models import parcel, scan\n\n\ndef current_scans(connection, carrier_id):\n    """Return one current scan for every parcel belonging to a carrier."""\n    latest = (select(scan.c.parcel_id, scan.c.id.label("scan_id"), scan.c.recorded_at,\n                     scan.c.depot, scan.c.condition)\n              .join(parcel, parcel.c.id == scan.c.parcel_id)\n              .where(parcel.c.carrier_id == carrier_id)\n              .distinct(scan.c.parcel_id)\n              .order_by(scan.c.parcel_id, scan.c.id.desc()))\n    return [dict(row) for row in connection.execute(latest).mappings()]\n\n\ndef scan_volume(connection, carrier_id):\n    """Existing operations summary; zero is meaningful."""\n    query = select(func.count(scan.c.id)).select_from(scan.join(parcel)).where(\n        and_(parcel.c.carrier_id == carrier_id, scan.c.condition != "cancelled"))\n    return connection.scalar(query)\n', "source anchor changed"
p.write_text('from sqlalchemy import and_, func, select\n\nfrom freight.models import parcel, scan\n\n\ndef current_scans(connection, carrier_id):\n    """Return one current scan for every parcel belonging to a carrier."""\n    latest = (select(scan.c.parcel_id, scan.c.id.label("scan_id"), scan.c.recorded_at,\n                     scan.c.depot, scan.c.condition)\n              .join(parcel, parcel.c.id == scan.c.parcel_id)\n              .where(parcel.c.carrier_id == carrier_id)\n              .distinct(scan.c.parcel_id)\n              .order_by(scan.c.parcel_id, scan.c.recorded_at.desc(), scan.c.id.desc()))\n    return [dict(row) for row in connection.execute(latest).mappings()]\n\n\ndef scan_volume(connection, carrier_id):\n    """Existing operations summary; zero is meaningful."""\n    query = select(func.count(scan.c.id)).select_from(scan.join(parcel)).where(\n        and_(parcel.c.carrier_id == carrier_id, scan.c.condition != "cancelled"))\n    return connection.scalar(query)\n')
PYFIX
